### ISSUE TITLE
编译打包出来的dist目录中产生大量js文件

### ISSUE THREAD

**Issue by slinzhang007** [WeBankFinTech/WeBASE-Web#221]
v1.3.2+的版本，我用npm run build打包出来dist目标，在dist目录下出现大量js文件，我不懂前端，所以不知道什么原因。对比不同的版本发现，v1.3.0是不会的， v1.3.1的版本就开始会这样。 我查找了很久，后来我无意中发现src/views/parseAbi/index.vue中有一行import "ace-builds/webpack-resolver";   源码中有其他地方有两处也有这行代码，但是注释了，于是我就把这行代码也注释掉，终于，dist目录中不会产生大量js文件了。 有人能告诉我什么原因吗? 注释掉这行的话对其他地方有没有影响？

**Comment by gongdaxia** [comment]
这是ide插件ace-builds打包生成的文件，注释不会影响功能，但是控制台会出现找不到资源的错误信息。如果嫌麻烦就注释掉吧，另外src/views/chaincode/components/code.vue  也有引用，注释就一起注释吧
